root FRAME x=0 y=0 w=1800 h=1000 "Erzieherausbildung Lernfeldlandkarte"
source STICKY parent=root x=200 y=200 w=260 color=light_blue "Quelle: erzieherausbildung"
fields STICKY parent=root x=700 y=200 w=300 color=cyan "Lernfelder + Sinnachsen"
outputs STICKY parent=root x=1200 y=200 w=300 color=violet "Web · Canvas · Miro"
e1 CONNECTOR from=source to=fields shape=elbowed end_cap=arrow "strukturieren"
e2 CONNECTOR from=fields to=outputs shape=elbowed end_cap=arrow "darstellen"
